config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'search'
    end
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
   validates :name, presence: true
   has_many :users, through: :group_users
   has_many :group_users
   has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, unless:'image.present?'
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages

  scope :search_user, ->(name){ where('name LIKE(?)', "%#{
    name}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

before_action :find_group, only: [:edit, :update]

  def index
    @groups = current_user.groups.order("created_at DESC")
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice:'グループを作成しました'
    else
      flash.now[:alert] = 'グループ名を入力してください'
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice:'グループを編集しました'
    else
      flash.now[:alert] = 'グループ名を表示してください'
      render :edit
    end
  end

  def search
    @users = User.where.not(id: current_user.id).search_user(params[:keyword])
    respond_to do |format|
      format.json
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :create_instance, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json {
        @messages = @group.messages.where('id > ?', params[:id])
      }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
       format.html { redirect_to group_messages_path, notice:'メッセージを作成しました' }
       format.json
    end

    else
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

  def create_instance
    @group = Group.find(params[:group_id])
    @groups = current_user.groups.order("created_at DESC")
    @messages = @group.messages
    @users = @group.users
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
.chat-group-form
  %h1= title
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, placeholder: :"グループ名を入力してください", class: 'chat-group-form__input'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :users, "チャットメンバーを追加", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :users, value: '', placeholder: :"追加したいユーザーを入力してください", class: 'chat-group-form__input'
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :users, 'チャットメンバー', class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = hidden_field_tag "group[user_ids][]", current_user.id
            %p.chat-group-user__name
              = current_user.name

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: 'chat-group-form__action-btn'

app/views/groups/_group.html.haml
=link_to group_messages_path(group), 'data-turbolinks': false do
  .chat-side__groups_name
    = group.name
  .chat-side__groups_message
    = group.messages.last.try(:body) ||'まだメッセージはありません'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', collection: @groups

app/views/groups/index.html.haml
.chat-side
 .chat-side__user
  .chat-side__user_name
   = current_user.name
  = link_to edit_user_registration_path do
   %i.fa.fa-cog.fa-fw
  = link_to new_group_path do
   %i.fa.fa-pencil-square-o.fa-fw
 .chat-side__groups
  = render @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', collection: @groups

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_header.html.haml
= link_to edit_group_path(@group) do
  Edit
.chat-main__header_name
  = @group.name
.chat-main__header_member
  Menbers:
  = @users.pluck(:name)

app/views/messages/_message.html.haml
.chat-main__body_chat{ "data-message-id": "#{message.id}"}
  .chat-main__body_chat-name
    = message.user.name
  .chat-main__body_chat-date
    = message.created_at
  .chat-main__body_chat-message
    = message.body
  %image.chat-main__body_chat-image{src: "#{message.image.url}"}

app/views/messages/index.html.haml
.chat-side
  .chat-side__user
    .chat-side__user_name
      = current_user.name
    = link_to edit_user_registration_path do
      %i.fa.fa-cog.fa-fw
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o.fa-fw

  .chat-side__groups
    = render @groups

.chat-main
  .chat-main__header
    = render 'header'
  .chat-main__body
    = render @messages
  .chat-main__footer
    = form_for [@group,@message] do |f|
      = f.text_field :body, placeholder: "type a message",class: 'textarea'
      = f.label :image do
        = f.file_field :image, style: "display:none;"
        %i.fa.fa-picture-o
      = f.submit "Send", class: 'input'